// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htvjlttlikjhmthbxtvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0dmpsdHRsaWtqaG10aGJ4dHZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MTg2MTgsImV4cCI6MjA1OTI5NDYxOH0.xDZRS5uhBrjgdtxWL9m-5EJ7yfWLZh8eH_-iR-fjUgc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);